<map version="1.0.1">
<node TEXT="MainActivity"><node TEXT="Start-Start-0"><node TEXT="Steps"><node TEXT="/*"></node>
</node>
</node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/mainContent&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/home_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/recommend_layout_refresh&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/recommend_recycler_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_header_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/name_layout&quot;]//*[@text=&quot;仙源游侠&quot; and @resource-id=&quot;com.xueqiu.android:id/userName&quot;]"><node TEXT="UserProfileActivity"><node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_header_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/name_layout&quot;]//*[@text=&quot;仙源游侠&quot; and @resource-id=&quot;com.xueqiu.android:id/userName&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/trade_opportunity&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/card_tag&quot;]//*[@text=&quot;股民的日常&quot; and @resource-id=&quot;com.xueqiu.android:id/name&quot;]"><node TEXT="TopicWordActivity"><node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_header_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/name_layout&quot;]//*[@text=&quot;粹语&quot; and @resource-id=&quot;com.xueqiu.android:id/userName&quot;]"></node>
</node>
</node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_header_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/name_layout&quot;]//*[@text=&quot;粹语&quot; and @resource-id=&quot;com.xueqiu.android:id/userName&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_header_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/profileImage&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/profileImage&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_foot_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/normal_answer_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/reward_count_view&quot;]//*[@text=&quot;1&quot; and @resource-id=&quot;com.xueqiu.android:id/reward_snowcoin&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_foot_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/normal_answer_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/reward_count_view&quot;]//*[@text=&quot;2&quot; and @resource-id=&quot;com.xueqiu.android:id/reward_snowcoin&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_foot_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/normal_answer_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/more_action_button&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/action_bar_root&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/coordinator&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/design_bottom_sheet&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/more_action_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/favorite&quot;]//*[@text=&quot;收藏&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/indicator_ll&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/refresh_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/status_card_foot_id&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/normal_answer_layout&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/retweet_count_view&quot;]"></node>
</node>
</node>
</node>
</map>