pip install requests
pip install jenkinsapi
pip install pytest
pip install PyMySQL
pip install Faker
pip install PyYAML
pip install Appium-Python-Client
pip install allure-pytest
pip install selenium
pip install pytest-rerunfailures
pip install pytest-assume
pip install pytest-ordering
pip install pytest-dependency
pip install pytest-xdist
pip install pytest-sugar
pip install jsonpath
pip install mitmproxy
pip install deepdiff
pip install pystache
pip install uiautomator2
pip install -U weditor
