<map version="1.0.1">
<node TEXT="MainActivity"><node TEXT="Start-Start-0"><node TEXT="Steps"><node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/mainContent&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/home_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/appbar&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/home_search&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/search_input_text&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_suggest&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/listview&quot;]//*[@text=&quot;阿里巴巴-SW&quot; and @resource-id=&quot;com.xueqiu.android:id/name&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/ll_search_result&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/vp_view_pager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/layout_refresh&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/list&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/ll_stock_result_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/ll_stock_item_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/stock_layout&quot;]//*[@text=&quot;09988&quot; and @resource-id=&quot;com.xueqiu.android:id/stockCode&quot;]"><node TEXT="StockDetailActivity"><node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/tab_indicator_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/tab_text_container&quot;]//*[@text=&quot;讨论&quot; and @resource-id=&quot;com.xueqiu.android:id/text&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/tab_indicator_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/tab_text_container&quot;]//*[@text=&quot;资金&quot; and @resource-id=&quot;com.xueqiu.android:id/text&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;分时&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;五日&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;日K&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;周K&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;月K&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;季K&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;年K&quot;]"></node>
<node TEXT="//*[@resource-id=&quot;com.xueqiu.android:id/decor_content_parent&quot;]//*[@resource-id=&quot;android:id/content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/viewPager&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/main_content&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/abl_header&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/fl_chart_view&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_fragment_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_chart_stock_info_container&quot;]//*[@resource-id=&quot;com.xueqiu.android:id/small_period_container&quot;]//*[@text=&quot;分钟&quot;]"></node>
<node TEXT="Back-15"></node>
<node TEXT="Back-16"><node TEXT="USearchActivity"><node TEXT="Back-17"></node>
</node>
</node>
</node>
</node>
</node>
</node>
<node TEXT="Back-18"><node TEXT="Launcher"><node TEXT="Back-19"></node>
<node TEXT="Back-20"></node>
<node TEXT="Back-21"></node>
</node>
</node>
</node>
</map>